cloud:
  aws:
    credentials:
      access-key: AKIATJTIH3FC5B4K6A6T
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: acbucket487384783


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

